SOproject/Controllers/SalesOrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Product.DataAccess.Base.Enum;
using Product.DataAccess.Enum;
using SOproject.CustomModel;
using SOproject.Models;
using SOproject.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace SOproject.Controllers
{
    public class SalesOrderController : Controller
    {
        private readonly ISalesOrderRepository _salesOrderRepository; 
        private readonly ISalesOrderLinesRepository _salesOrderLinesRepository; 
        private readonly IMapper _mapper;
        private readonly HttpClient _client;
        private readonly IHttpClientFactory _httpClientFactory;

        
        public SalesOrderController(ISalesOrderRepository salesOrdersRepository, ISalesOrderLinesRepository salesOrderLinesRepository, IMapper mapper, IHttpClientFactory httpClientFactory)
        {
            _salesOrderRepository = salesOrdersRepository;
            _salesOrderLinesRepository = salesOrderLinesRepository;
            _mapper = mapper;
            _client = CreateHttpClientWithNTLM();
            _httpClientFactory = httpClientFactory;

        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> IndexDBAjax([FromBody] SalesOrderCM model)
        {
            var list = _salesOrderRepository.GetAllAsyncPage(model.PageNo,model.PageSize);
            var list2 = new List<SlaesOrderHeaderAndLines.Value>();

          
            list2 = list.Item1.Select(c => new SlaesOrderHeaderAndLines.Value()
            {
                No = c.Number,
                Sell_to_Customer_Name = c.CustomerName,
                Posting_Description = c.Description,
                Order_Date = c.OrderDate.ToShortDateString(),
                Phone_No = c.PhoneNumber,
                Shipment_Date = c.ShipmentDate.ToShortDateString(),
                CRM_Cost_Amount = c.Ammount.ToString(),
                SalesOrderSalesLines = null
            }).ToList();

            return Json(new
            {
                TotalItems = list.Item2,
                Data = list2
            });
        }

        public async Task<JsonResult> IndexAjax([FromBody] SalesOrderCM model)
        {
            var resultt = await _client.GetAsync($@"{_client.BaseAddress}/SalesOrder?$filter={model.Number}");
            var NotofocationList = JsonConvert.DeserializeObject<SlaesOrderHeaderAndLines.Rootobject>(await resultt.Content.ReadAsStringAsync());
          
            return Json(new
            {
                TotalItems = 3,
                Data = NotofocationList.value
            });
        }
        public HttpClient CreateHttpClientWithNTLM()
        {
            var url = "http://ns-hou-navdev01.netsync.com:9837/DEVNETSYNC2018/ODataV4/Company(";

            var uri = new Uri($"{url}'NetSync%20Network%20-%20Live')");
            var credentialsCache = new CredentialCache { { uri, "NTLM", new NetworkCredential("sales", "Netsync01") } };
            var handler = new HttpClientHandler { Credentials = credentialsCache };
            var httpClient = new HttpClient(handler) { BaseAddress = uri };
            httpClient.DefaultRequestHeaders.ConnectionClose = false;
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            ServicePointManager.FindServicePoint(uri).ConnectionLeaseTimeout = 120 * 1000;  // Close connection after two minutes

            return httpClient;
        }

        public async Task<IActionResult> _Details(string soNo)
        {
           return PartialView( new SalesOrderCM() { Number=soNo }); ;
        }

        public async Task<IActionResult> DetailsAjax([FromBody]SalesOrderCM model)
        {
            var data =new List<SlaesOrderHeaderAndLines.Salesordersalesline>();
            var count = 0;
            if (_salesOrderRepository.Find(model.Number) != null)
            {
                var all = _salesOrderLinesRepository.GetQueryable(c => c.SalesOrder.Number.Equals(model.Number)) ;
                data = all.Select(v => new SlaesOrderHeaderAndLines.Salesordersalesline()
                {
                    No = v.Number,
                    Description = v.Description,
                    Quantity = v.Quantity,
                    Job_No = v.JobNumber,
                    Unit_Price = v.UnitPrice
                }).ToList();
                count = data.Count();
            }
            else { 
                var resultt = await _client.GetAsync($@"{_client.BaseAddress}/SalesOrder?$filter=No eq '{model.Number}'&$expand=SalesOrderSalesLines");
                var NotofocationList = JsonConvert.DeserializeObject<SlaesOrderHeaderAndLines.Rootobject>(await resultt.Content.ReadAsStringAsync());
                count = NotofocationList.value[0].SalesOrderSalesLines.Count();
                data = NotofocationList.value[0].SalesOrderSalesLines.ToList();
            }          
            return Json(new
            {
                TotalItems = count,
                Data = data
            }) ;
        }

        [HttpPost]
        public async Task<IActionResult> SaveToDB([FromBody]string No)
        {
            
            if (_salesOrderRepository.Find(No) != null)
            {
                return Json(new
                {
                    status = JsonStatus.Exist,
                    color = NotificationColor.Error.ToColorName(),
                    management = "SalesOrder Management",
                    msg = "This SalesOrder is already saved in DB.",
                });
            }
            else
            {
                var getapi = await _client.GetAsync($@"{_client.BaseAddress}/SalesOrder?$filter=No eq '{No}'&$expand=SalesOrderSalesLines");
                var SOLineList = JsonConvert.DeserializeObject<SlaesOrderHeaderAndLines.Rootobject>(await getapi.Content.ReadAsStringAsync());
                var SO = SOLineList.value[0];
                var SOLines = SOLineList.value[0].SalesOrderSalesLines.ToList();

                var res =  await _salesOrderRepository.AddAsync(new SalesOrder()
                {
                    Number = SO.No,
                    CustomerName = SO.Sell_to_Customer_Name,
                    Description = SO.Posting_Description,
                    OrderDate = Convert.ToDateTime(SO.Order_Date),
                    PhoneNumber = SO.Phone_No,
                    ShipmentDate = Convert.ToDateTime(SO.Shipment_Date),
                    Ammount = Convert.ToDecimal(SO.CRM_Cost_Amount)
                });

                if (res > 0)
                {
                    foreach (var sol in SOLines)
                    {
                        await _salesOrderLinesRepository.AddAsync(new SOLines()
                        {
                            Number = sol.No,
                            Description = sol.Description,
                            Quantity = sol.Quantity,
                            JobNumber = sol.Job_No,
                            UnitPrice = sol.Unit_Price,
                            SalesOrder = _salesOrderRepository.Find(SO.No)
                        });
                    }
                    return Json(new
                    {
                        status = JsonStatus.Success,
                        color = NotificationColor.Success.ToColorName(),
                        management = "SalesOrder Management",
                        msg = "The SalesOrder is saved succesfully.",
                    });
                }
                else
                    return Json(new
                    {
                        status = JsonStatus.Error,
                        color = NotificationColor.Error.ToColorName(),
                        management = "SalesOrder Management",
                        msg = "Error Happened",
                    });
            }

        }
    }
}

SOproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SOproject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
    <link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-balham.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap4-toggle.min.css" rel="stylesheet" />
    <link href="~/img/plugins.bundle.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/site.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SOproject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesOrder" asp-action="Index">Sales Order</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SOproject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <div class="modal fade" id="OpenModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content modal-scroll-content">

            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.bundle.js"></script>
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap4-toggle.min.js"></script>
    <script src="~/img/plugins.bundle.js"></script>

    <script src="~/lib/Jquery-overlaysScrollbars/jquery.overlayScrollbars.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha256-yNbKY1y6h2rbVcQtf0b8lq4a+xpktyFc3pSYoGAY1qQ=" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>